version: "3"
services:
  frontend:
    container_name: frontend
    image: sandropxl/musicdeck:pi-fe
    ports:
      - "5500:80"
    restart: always
  backend:
    container_name: backend
    image: sandropxl/musicdeck:pi-be
    ports:
      - "8888:8888"
    env_file:
      - ../.env
    devices:
      - /dev:/dev
    privileged: true
    restart: always
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_SCHEDULE=*/15 * * * * *
    volumes:
        - /etc/localtime:/etc/localtime
        - /var/run/docker.sock:/var/run/docker.sock
    restart: always