FROM balenalib/raspberrypi4-64-debian-node:18-bullseye
ENV BALENA_DEV=1
WORKDIR /usr/src/app
COPY package*.json api.js read_rfid.py ./
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-setuptools \
    libpython3-dev \
    build-essential \
    git \
    libpcsclite-dev \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install RPi.GPIO mfrc522
RUN npm install
CMD ["node", "api.js"]