name: docker image backend

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - api.js
      - docker/Dockerfile-be
  workflow_dispatch:

jobs:
  docker-be:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push Docker image backend
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/musicdeck:pi-be
          file: ./docker/Dockerfile-be       
          platforms: linux/arm64 