name: docker image frontend

on:
  push:
    branches:
      - main
    paths:
      - index.html
      - player.js
      - style.css
      - config.js
      - read_rfid.py
      - imgs/**
      - docker/Dockerfile-fe
  workflow_dispatch:

jobs:
  docker-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image frontend
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/musicdeck:pi-fe
          file: ./docker/Dockerfile-fe
          platforms: linux/arm64